version: '3.5'
services:
    postgres:
        container_name: postgres_container
        image: postgres
        volumes:
            - crowndly_postgres:/data/postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: crowdly
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            PGDATA: /data/postgres
        restart: unless-stopped
            
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            MASTER_PASSWORD_REQUIRED: 'False'
            PGADMIN_DEFAULT_EMAIL: test@test.com
            PGADMIN_DEFAULT_PASSWORD: pass
        volumes:
           - crowndly_pgadmin:/root/.pgadmin

        ports:
            - 5050:80
        restart: unless-stopped

volumes:
        crowndly_postgres:
        crowndly_pgadmin: